version: "3.12"

services:
  web:
    build: .
    container_name: chatbot_django
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /chatbot
    ports:
      - "8000:8000"
    volumes:
      - .:/chatbot


